# Generated by Django 2.2.2 on 2021-04-10 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210410_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='building_id',
            field=models.CharField(default='', max_length=10),
        ),
    ]
