# Generated by Django 2.2.2 on 2021-04-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('building_name', models.CharField(max_length=30)),
                ('building_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='BuildingRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_id', models.CharField(choices=[('just_built', 'just_built')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CoordRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.CharField(max_length=25)),
                ('latitude', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name_plural': 'coordRequests',
            },
        ),
        migrations.CreateModel(
            name='NameRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name_plural': 'nameRequests',
            },
        ),
    ]
