# Generated by Django 2.2.2 on 2021-04-05 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buildingrequest',
            options={'verbose_name_plural': 'buildingRequests'},
        ),
        migrations.AlterField(
            model_name='building',
            name='building_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
