# Generated by Django 2.2.2 on 2021-04-05 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_auto_20210405_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingrequest',
            name='building_id',
            field=models.CharField(max_length=50),
        ),
    ]
