# Generated by Django 2.2.2 on 2021-04-10 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_auto_20210405_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='latitude',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='longitude',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='owner_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
