# Generated by Django 2.2.2 on 2021-04-11 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0005_auto_20210411_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='building_city',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
