# Generated by Django 2.2.2 on 2021-04-11 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0006_building_building_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='temp_t',
            field=models.IntegerField(null=True),
        ),
    ]
