# Generated by Django 2.2.2 on 2021-04-15 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0007_building_temp_t'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='temp_t',
        ),
    ]
