# Generated by Django 2.2.2 on 2021-04-15 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0008_remove_building_temp_t'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='temp_too_high',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='building',
            name='temp_too_low',
            field=models.BooleanField(default=False),
        ),
    ]
