# Generated by Django 2.2.2 on 2021-04-15 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0009_auto_20210415_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='temperature_object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_temp', models.FloatField(null=True)),
                ('min_temp', models.FloatField(null=True)),
                ('date', models.DateField()),
            ],
        ),
    ]
