# Generated by Django 2.2.2 on 2021-05-21 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0010_temperature_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='db_yesterday_max',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='db_yesterday_min',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='yesterday_max',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='yesterday_min',
            field=models.FloatField(null=True),
        ),
    ]
