# Generated by Django 2.2.2 on 2021-05-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0011_auto_20210521_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='till_now_max',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='till_now_min',
            field=models.FloatField(null=True),
        ),
    ]
