# Generated by Django 2.2.2 on 2021-05-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0012_auto_20210521_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='last_update_date',
            field=models.DateField(null=True),
        ),
    ]
